version: '3'
services:
  db:
    restart: always
    image: postgres:11.5-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./app.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    restart: always
    build:
      context: .
      dockerfile: ./web.Dockerfile
    volumes:
      - .:/var/www/myapp
    depends_on:
      - app
    ports:
      - "80:80"
