version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    restart: always
    env_file:
      - .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      - db